/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/boards/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Boards */
        get: operations["get_boards_api_boards__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs */
        get: operations["get_runs_api_runs__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sectors/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sectors */
        get: operations["get_sectors_api_sectors__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Board
         * @description One market's leaderboard for a single lookback (spec §5.2).
         */
        Board: {
            /** Lookback */
            lookback: string;
            /** Rows */
            rows: components["schemas"]["BoardRow"][];
        };
        /**
         * BoardRow
         * @description One leaderboard row: a name ranked on **pure return**, plus its furniture
         *     (spec §4.3 / ticket 06). ``breadth`` is the ``k/5`` badge (lookbacks currently
         *     led — a persistence count, *not* a quality score); ``is_new`` marks absence
         *     from this board last session; ``surge`` flags a 1w name up ≥30% over the week;
         *     ``adr`` is a column for the toggle, never the sort key, ``None`` when it cannot
         *     be computed.
         */
        BoardRow: {
            /** Adr */
            adr: number | null;
            /** Breadth */
            breadth: number;
            /** Is New */
            is_new: boolean;
            /** Raw Return */
            raw_return: number;
            /** Surge */
            surge: boolean;
            /** Symbol */
            symbol: string;
        };
        /**
         * BoardsResponse
         * @description The five leaderboards for one market, off the nightly path (spec §5.2).
         *
         *     ``session`` is the as-of session the boards were ranked on — the latest
         *     published run — or ``None`` when no run has published yet, which the tab shows
         *     as an explicit empty state.
         */
        BoardsResponse: {
            /** Boards */
            boards: components["schemas"]["Board"][];
            /** Market */
            market: string;
            /** Session */
            session: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndustryStrength
         * @description One ranked industry's shares (spec §4.4 / ticket 07 S5).
         *
         *     An industry is ranked only at ``members ≥ 10`` — one rule, both markets,
         *     yielding many more rows on US than IDX. Industry *is* the theme layer (S1).
         */
        IndustryStrength: {
            /** Decile Counts */
            decile_counts: {
                [key: string]: number;
            };
            /** Industry */
            industry: string;
            /** Members */
            members: number;
            /** Sector */
            sector: string;
            /** Shape Differential */
            shape_differential: number;
            /** Shares */
            shares: {
                [key: string]: number;
            };
        };
        /**
         * RunRecord
         * @description One row of the append-only ``runs`` table, keyed ``(market, session)``.
         */
        RunRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Market */
            market: string;
            /**
             * Session
             * Format: date
             */
            session: string;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "quarantined";
            /** Symbols Enumerated */
            symbols_enumerated: number;
            /** Symbols Resolved */
            symbols_resolved: number;
        };
        /**
         * RunsResponse
         * @description Run records for one market, newest first.
         *
         *     ``latest`` is the last *published* run — the as-of session the tab renders.
         *     It is ``None`` when no run has published yet, which the tab shows as an
         *     explicit empty state rather than a blank or a fabricated date.
         */
        RunsResponse: {
            latest: components["schemas"]["RunRecord"] | null;
            /** Market */
            market: string;
            /** Runs */
            runs: components["schemas"]["RunRecord"][];
            /** Universe Size */
            universe_size: number | null;
        };
        /**
         * SectorStrength
         * @description One sector's leadership and rotation numbers (spec §4.4 / ticket 07 S2–S8).
         *
         *     ``shares`` carries the five per-lookback strengths — the share of this
         *     sector's members in that lookback's top decile, ``k/n``. ``members`` is
         *     ``n`` (the sector's universe count) and ``decile_counts`` is ``k`` per
         *     lookback, so the UI can render the ``k/n`` fragility badge (S4).
         */
        SectorStrength: {
            /** Decile Counts */
            decile_counts: {
                [key: string]: number;
            };
            /** Delta Low Confidence */
            delta_low_confidence: boolean;
            /** Members */
            members: number;
            /** Rotation Eligible */
            rotation_eligible: boolean;
            /** Sector */
            sector: string;
            /** Shape Differential */
            shape_differential: number;
            /** Shares */
            shares: {
                [key: string]: number;
            };
            /** Temporal Delta */
            temporal_delta: number | null;
        };
        /**
         * SectorsResponse
         * @description The sector board and the ranked-industry board for one market (§4.4).
         *
         *     ``sectors`` is always the full 11-sector axis, default-sorted by shape
         *     differential with the rotation-ineligible sectors grouped below (S4/S8).
         *     ``industries`` carries only the ``members ≥ 10`` rows. ``session`` is the
         *     as-of published session, ``None`` when no run has published.
         */
        SectorsResponse: {
            /** Industries */
            industries: components["schemas"]["IndustryStrength"][];
            /** Market */
            market: string;
            /** Sectors */
            sectors: components["schemas"]["SectorStrength"][];
            /** Session */
            session: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_boards_api_boards__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_api_runs__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sectors_api_sectors__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
