/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/boards/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Boards */
        get: operations["get_boards_api_boards__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidates */
        get: operations["get_candidates_api_candidates__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chart/{market}/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chart */
        get: operations["get_chart_api_chart__market___symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaders/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaders */
        get: operations["get_leaders_api_leaders__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regime/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Regime */
        get: operations["get_regime_api_regime__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runs */
        get: operations["get_runs_api_runs__market__get"];
        put?: never;
        /** Trigger Run */
        post: operations["trigger_run_api_runs__market__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sectors/{market}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sectors */
        get: operations["get_sectors_api_sectors__market__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Candidate
         * @description One row of the candidate list — a detection made readable (spec §5.1 / §4.3).
         *
         *     ``score`` is the star score (0–5) and the sort key of the list; ``breakdown``
         *     carries its eight-row rubric so the row (or the chart panel) can reconstruct
         *     the arithmetic (spec §4.7). ``dist_adr`` is the distance to the trigger in ADR
         *     (``(trigger − close) / adr_abs``); ``stopw_adr`` is the stop width in ADR
         *     (``(trigger − cluster_low) / adr_abs``, the watchlist stop of §4.6). The stop
         *     column **never filters** — instead the affordable sub-1×ADR minority is flagged
         *     (``affordable``), the inverse of marking the ~92% unaffordable majority.
         *     ``industry`` is the theme layer (``None`` if the label was never fetched);
         *     ``breadth`` is the ``k/5`` badge, a persistence count and **not** a quality
         *     score.
         *
         *     The **chart-facts fold** (spec §4.3): so a Setups card can show trigger, stop
         *     and distance without a per-symbol chart fetch, the fields that lived only in
         *     the chart bundle now ride the row too — projected from the *same* detection,
         *     which is the single source both endpoints render from. ``trigger_price`` /
         *     ``stop_price`` are the **borrowed** names for the overlay's trigger (cluster
         *     high) and stop (cluster low) — v1 had no word for them; ``risk_adr`` is
         *     **refused** (that quantity is ``stopw_adr`` and keeps its name). ``sector`` is
         *     new on this row, which carried ``industry`` only; both are wanted.
         *     ``dollar_volume`` and ``sector`` are ``None`` when the bars/label could not
         *     supply them, and ``decile_ranks`` omits a lookback the name is not ranked in —
         *     mirroring the chart facts block exactly.
         *
         *     ``new_tonight`` (P1) is true exactly for names absent from the previous
         *     session's detected rows — the row-level fact that replaces the reference's
         *     standalone new-ready panel. ``verdict`` (P2) is typed now and returned ``None``.
         *     ``breakdown`` is typed nullable because at P2 the list will carry non-``detected``
         *     rows whose star score is undefined; on a P1 detected row it is always the
         *     eight-row rubric.
         *
         *     Nothing here marks a ``line_ok`` failure: the fit's quality is a **silent
         *     tiebreak** that orders the list but is never surfaced in the row (spec §4.7).
         */
        Candidate: {
            /** Adr */
            adr: number;
            /** Affordable */
            affordable: boolean;
            /** Breadth */
            breadth: number;
            /** Breakdown */
            breakdown: components["schemas"]["ScoreRow"][] | null;
            /** Close */
            close: number;
            /** Decile Ranks */
            decile_ranks: {
                [key: string]: number;
            };
            /** Dist Adr */
            dist_adr: number;
            /** Dollar Volume */
            dollar_volume: number | null;
            /** Industry */
            industry: string | null;
            /** New Tonight */
            new_tonight: boolean;
            /** Score */
            score: number;
            /** Sector */
            sector: string | null;
            /** Stop Price */
            stop_price: number;
            /** Stopw Adr */
            stopw_adr: number;
            /** Symbol */
            symbol: string;
            /** Trigger Price */
            trigger_price: number;
            /** Verdict */
            verdict?: string | null;
        };
        /**
         * CandidatesResponse
         * @description Tonight's candidate list for one market (spec §5.1).
         *
         *     ``session`` is the as-of published session, ``None`` when no run has
         *     published (an explicit empty state). ``ordered_by`` is ``"score"`` now that
         *     the star-score rubric lands (ticket 39): the list sorts by star score
         *     descending, with ``line_ok`` failures silently below equal-scored accepted
         *     names. The field remains for the UI to read the order honestly.
         */
        CandidatesResponse: {
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Market */
            market: string;
            /**
             * Ordered By
             * @enum {string}
             */
            ordered_by: "ticker" | "score";
            /** Session */
            session: string | null;
        };
        /**
         * Candle
         * @description One OHLCV bar for the chart, **unadjusted** — real price levels the trigger
         *     and stop rules are placed at (spec §5.1 / §3.5). ``session`` is the trading
         *     date; the frontend renders these as candlesticks and the volume histogram.
         */
        Candle: {
            /** Close */
            close: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Open */
            open: number;
            /**
             * Session
             * Format: date
             */
            session: string;
            /** Volume */
            volume: number;
        };
        /**
         * ChartFacts
         * @description The facts block beside the chart (spec §5.1): the numbers the row deliberately
         *     left off, read here where the trade decision is made.
         *
         *     Populated from the name's detection row (``base_len``, ``trigger``,
         *     ``dist_adr``, ``stopw_adr``, ``adr``), its bars (``dollar_volume``, the §4.1
         *     median-20d liquidity), its rank rows (``decile_ranks``, percentile per
         *     lookback) and the label cache (``sector``). ``None`` for the whole block when
         *     the symbol has no detection tonight — the chart still draws, but there is no
         *     base to describe.
         */
        ChartFacts: {
            /** Adr */
            adr: number;
            /** Base Len */
            base_len: number;
            /** Decile Ranks */
            decile_ranks: {
                [key: string]: number;
            };
            /** Dist Adr */
            dist_adr: number;
            /** Dollar Volume */
            dollar_volume: number | null;
            /** Sector */
            sector: string | null;
            /** Stopw Adr */
            stopw_adr: number;
            /** Trigger */
            trigger: number;
        };
        /**
         * ChartResponse
         * @description One symbol's evidence bundle — the chart panel in a single call (spec §5.1).
         *
         *     Candles plus the daily MA set (SMA 10/20/50 and the 65 EMA, spec §2) as line
         *     series, the ``setup`` overlay (base/cluster shading, envelope, trigger/stop and
         *     the §4.7 breakdown) and the facts block. ``session`` is the as-of published
         *     session, or ``None`` when no run has published (an explicit empty state). The
         *     MA lines are computed over the full stored history and then sliced to the drawn
         *     window, so the first drawn point already carries a full window behind it.
         */
        ChartResponse: {
            /** Candles */
            candles: components["schemas"]["Candle"][];
            /** Ema65 */
            ema65: components["schemas"]["MaPoint"][];
            facts: components["schemas"]["ChartFacts"] | null;
            /** Market */
            market: string;
            /** Session */
            session: string | null;
            setup: components["schemas"]["SetupOverlay"] | null;
            /** Sma10 */
            sma10: components["schemas"]["MaPoint"][];
            /** Sma20 */
            sma20: components["schemas"]["MaPoint"][];
            /** Sma50 */
            sma50: components["schemas"]["MaPoint"][];
            /** Symbol */
            symbol: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndustryStrength
         * @description One ranked industry's shares (spec §4.4 / ticket 07 S5).
         *
         *     An industry is ranked only at ``members ≥ 10`` — one rule, both markets,
         *     yielding many more rows on US than IDX. Industry *is* the theme layer (S1).
         */
        IndustryStrength: {
            /** Decile Counts */
            decile_counts: {
                [key: string]: number;
            };
            /** Industry */
            industry: string;
            /** Members */
            members: number;
            /** Sector */
            sector: string;
            /** Shape Differential */
            shape_differential: number;
            /** Shares */
            shares: {
                [key: string]: number;
            };
        };
        /**
         * Leader
         * @description One market's leaderboard for a single lookback (spec §5.2 / §5.3).
         *
         *     ``cutoffs`` is a per-lookback block that sits **beside** the rows — the
         *     cutoff-return summary at the tier-band boundaries — never repeated on every
         *     row (spec §4.4). Phase-2, so ``None`` until the banding lands.
         */
        Leader: {
            /** Cutoffs */
            cutoffs?: {
                [key: string]: number;
            } | null;
            /** Lookback */
            lookback: string;
            /** Rows */
            rows: components["schemas"]["LeaderRow"][];
        };
        /**
         * LeaderRow
         * @description One leaderboard row: a name ranked on **pure return**, plus its furniture
         *     (spec §4.3 / §4.4 / ticket 06). ``breadth`` is the ``k/5`` badge (lookbacks
         *     currently led — a persistence count, *not* a quality score); ``is_new`` marks
         *     absence from this board last session; ``surge`` flags a 1w name up ≥30% over
         *     the week; ``adr`` is a column for the toggle, never the sort key, ``None`` when
         *     it cannot be computed.
         *
         *     ``sector`` and ``dollar_volume`` are the two **phase-1** additions (spec §4.4):
         *     both cheap, since the read already loads exactly these names' bars for the ADR
         *     column and sector is a store lookup. Without them the phase-1 control bar would
         *     ship with two live controls and two dead ones. ``sector`` is ``None`` when the
         *     label was never fetched; ``dollar_volume`` is ``None`` when the name's bars
         *     could not supply it, the same guard the ADR column carries.
         *
         *     ``tier`` and ``rs_pctile`` are **phase-2**, typed nullable and returning
         *     ``None`` until the cross-sectional tier banding lands in the run (spec §4.4).
         */
        LeaderRow: {
            /** Adr */
            adr: number | null;
            /** Breadth */
            breadth: number;
            /** Dollar Volume */
            dollar_volume: number | null;
            /** Is New */
            is_new: boolean;
            /** Raw Return */
            raw_return: number;
            /** Rs Pctile */
            rs_pctile?: number | null;
            /** Sector */
            sector: string | null;
            /** Surge */
            surge: boolean;
            /** Symbol */
            symbol: string;
            /** Tier */
            tier?: string | null;
        };
        /**
         * LeadersResponse
         * @description The five leaderboards for one market, off the nightly path (spec §5.2 /
         *     §5.3). Formerly ``/api/boards``; renamed because *Board* now names the
         *     composite home screen, with ``/api/boards`` kept as an alias (spec §10.2).
         *
         *     ``session`` is the as-of session the boards were ranked on — the latest
         *     published run — or ``None`` when no run has published yet, which the tab shows
         *     as an explicit empty state.
         */
        LeadersResponse: {
            /** Boards */
            boards: components["schemas"]["Leader"][];
            /** Market */
            market: string;
            /** Session */
            session: string | null;
        };
        /**
         * MaPoint
         * @description One point of a moving-average line series — the value at a session. The
         *     line skips the leading bars where the window has not yet filled, so a series
         *     is shorter than the candle series and starts later (spec §4.2).
         */
        MaPoint: {
            /**
             * Session
             * Format: date
             */
            session: string;
            /** Value */
            value: number;
        };
        /**
         * RegimeResponse
         * @description The market regime banner's payload — **advisory only** (spec §4.9).
         *
         *     Carries the three-state ``state``, its sizing posture in *words*, market
         *     ``breadth`` (share of the universe above its own rising SMA10/20, displayed
         *     and gating nothing), and the as-of ``session``. Two banners, one per market,
         *     never combined into a global verdict. The regime never filters, reorders or
         *     scores the candidate list — every field here is read and shown, none gates.
         *
         *     ``state`` is ``None`` when the regime is **undefined** (fewer than 25 index
         *     bars) or no run has published; ``session`` is ``None`` only in the latter
         *     case, which is how the banner tells "warming up" from "nothing yet". ``posture``
         *     is ``None`` whenever ``state`` is.
         */
        RegimeResponse: {
            /** Breadth */
            breadth: number | null;
            /** Market */
            market: string;
            /** Posture */
            posture: string | null;
            /** Session */
            session: string | null;
            /** State */
            state: ("FRIENDLY" | "CHOPPY" | "HOSTILE") | null;
        };
        /**
         * RunRecord
         * @description One row of the append-only ``runs`` table, keyed ``(market, session)``.
         */
        RunRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Market */
            market: string;
            /**
             * Session
             * Format: date
             */
            session: string;
            /**
             * Status
             * @enum {string}
             */
            status: "published" | "quarantined";
            /** Symbols Enumerated */
            symbols_enumerated: number;
            /** Symbols Resolved */
            symbols_resolved: number;
        };
        /**
         * RunTriggerResponse
         * @description The reply to a run-on-open ``POST /api/runs/{market}`` (spec §7.3).
         *
         *     ``triggered`` is true when this call started a run, false when one was
         *     already in flight (run-on-open is single-flight — a second open joins the
         *     running run rather than duplicating it). ``running`` is the market's state
         *     after the call: true whenever a run is in flight, so the tab polls until it
         *     clears and then reloads the now-complete session.
         */
        RunTriggerResponse: {
            /** Market */
            market: string;
            /** Running */
            running: boolean;
            /** Triggered */
            triggered: boolean;
        };
        /**
         * RunsResponse
         * @description Run records for one market, newest first.
         *
         *     ``latest`` is the last *published* run — the as-of session the tab renders.
         *     It is ``None`` when no run has published yet, which the tab shows as an
         *     explicit empty state rather than a blank or a fabricated date.
         */
        RunsResponse: {
            latest: components["schemas"]["RunRecord"] | null;
            /** Market */
            market: string;
            /**
             * Run Due
             * @default false
             */
            run_due: boolean;
            /** Run Error */
            run_error?: string | null;
            /**
             * Running
             * @default false
             */
            running: boolean;
            /** Runs */
            runs: components["schemas"]["RunRecord"][];
            /** Universe Size */
            universe_size: number | null;
        };
        /**
         * ScoreRow
         * @description One row of a candidate's star-score breakdown (spec §4.7).
         *
         *     Eight of these reconstruct the score arithmetically next to the chart — the
         *     dimension's name, its weight (2 for tightness and orderliness, 1 for the rest)
         *     and whether it hit. ``n/10 → stars`` is ``sum(weight where hit) ÷ 2``.
         */
        ScoreRow: {
            /** Dimension */
            dimension: string;
            /** Hit */
            hit: boolean;
            /** Weight */
            weight: number;
        };
        /**
         * SectorStrength
         * @description One sector's leadership and rotation numbers (spec §4.4 / ticket 07 S2–S8).
         *
         *     ``shares`` carries the five per-lookback strengths — the share of this
         *     sector's members in that lookback's top decile, ``k/n``. ``members`` is
         *     ``n`` (the sector's universe count) and ``decile_counts`` is ``k`` per
         *     lookback, so the UI can render the ``k/n`` fragility badge (S4).
         */
        SectorStrength: {
            /** Decile Counts */
            decile_counts: {
                [key: string]: number;
            };
            /** Delta Low Confidence */
            delta_low_confidence: boolean;
            /** Members */
            members: number;
            /** Rotation Eligible */
            rotation_eligible: boolean;
            /** Sector */
            sector: string;
            /** Shape Differential */
            shape_differential: number;
            /** Shares */
            shares: {
                [key: string]: number;
            };
            /** Temporal Delta */
            temporal_delta: number | null;
        };
        /**
         * SectorsResponse
         * @description The sector board and the ranked-industry board for one market (§4.4).
         *
         *     ``sectors`` is always the full 11-sector axis, default-sorted by shape
         *     differential with the rotation-ineligible sectors grouped below (S4/S8).
         *     ``industries`` carries only the ``members ≥ 10`` rows. ``session`` is the
         *     as-of published session, ``None`` when no run has published.
         */
        SectorsResponse: {
            /** Industries */
            industries: components["schemas"]["IndustryStrength"][];
            /** Market */
            market: string;
            /** Sectors */
            sectors: components["schemas"]["SectorStrength"][];
            /** Session */
            session: string | null;
        };
        /**
         * SetupOverlay
         * @description The setup drawn on top of the candles (spec §5.1 / §3.5 / ticket 41) — the
         *     chart as *evidence for the score*, not merely a price chart.
         *
         *     - ``base_start`` / ``cluster_start`` are the first sessions of the base and of
         *       the tight trailing cluster inside it; the frontend shades each region from
         *       its start to the last candle (the base always ends today, §4.5).
         *     - ``trigger`` (cluster high) and ``stop`` (cluster low) are the two horizontal
         *       rules §7's affordability test is read off geometrically.
         *     - ``envelope`` is the fitted upper line drawn **as a line series** so candles
         *       pierce it in both directions — per §3.2 that is the correct picture and must
         *       not be "fixed" in rendering. Anchored at the cluster's max-high bar with the
         *       detection's non-positive slope, so it can never exceed the trigger.
         *     - ``score`` (0–5 stars) and ``breakdown`` (the eight §4.7 dimensions, each with
         *       its weight and hit) reconstruct the sort key arithmetically beside the chart.
         *
         *     ``None`` for the whole overlay when the name has no detection tonight — there
         *     is no base to shade, no envelope to fit and no score to break down.
         */
        SetupOverlay: {
            /**
             * Base Start
             * Format: date
             */
            base_start: string;
            /** Breakdown */
            breakdown: components["schemas"]["ScoreRow"][];
            /**
             * Cluster Start
             * Format: date
             */
            cluster_start: string;
            /** Envelope */
            envelope: components["schemas"]["MaPoint"][];
            /** Score */
            score: number;
            /** Stop */
            stop: number;
            /** Trigger */
            trigger: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_boards_api_boards__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidates_api_candidates__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chart_api_chart__market___symbol__get: {
        parameters: {
            query?: {
                bars?: number | null;
            };
            header?: never;
            path: {
                market: string;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaders_api_leaders__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regime_api_regime__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegimeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_api_runs__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_run_api_runs__market__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTriggerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sectors_api_sectors__market__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
